RSVPApp/Models/ErrorViewModel.cs
namespace RSVPApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RSVPApp/Models/GuestRespond.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
namespace RSVPApp.Models
{
    public class RSVPContext : DbContext
    {
        public RSVPContext(){}
        public RSVPContext(DbContextOptions<RSVPContext> options) : base(options)
        {

        }
        public DbSet<GuestRespond> GuestRespond { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            if (!options.IsConfigured)
            {
                options.UseSqlServer(@"Server=JRFZN53;Database=RSVP;Trusted_Connection=True;ConnectRetryCount=0");
            }
        }

    }
    public class GuestRespond
    {
        public int GuestRespondId { get; set; }
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$")]
        [Required(ErrorMessage = "Please enter your email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter your phone")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Please specify whether you will attend")]
        public bool? Attend { get; set; }

    }
}

RSVPApp/Controllers/GuestRespondsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RSVPApp.Models;

namespace RSVPApp.Controllers
{
    public class GuestRespondsController : Controller
    {
        private readonly RSVPContext _context;

        public GuestRespondsController(RSVPContext context)
        {
            _context = context;
        }

        // GET: GuestResponds
        public async Task<IActionResult> Index()
        {
            return View(await _context.GuestRespond.ToListAsync());
        }

        // GET: GuestResponds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guestRespond = await _context.GuestRespond
                .FirstOrDefaultAsync(m => m.GuestRespondId == id);
            if (guestRespond == null)
            {
                return NotFound();
            }

            return View(guestRespond);
        }

        // GET: GuestResponds/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: GuestResponds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GuestRespondId,Name,Email,Phone,Attend")] GuestRespond guestRespond)
        {
            if (ModelState.IsValid)
            {
                _context.Add(guestRespond);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(guestRespond);
        }

        // GET: GuestResponds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guestRespond = await _context.GuestRespond.FindAsync(id);
            if (guestRespond == null)
            {
                return NotFound();
            }
            return View(guestRespond);
        }

        // POST: GuestResponds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GuestRespondId,Name,Email,Phone,Attend")] GuestRespond guestRespond)
        {
            if (id != guestRespond.GuestRespondId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(guestRespond);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GuestRespondExists(guestRespond.GuestRespondId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(guestRespond);
        }

        // GET: GuestResponds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guestRespond = await _context.GuestRespond
                .FirstOrDefaultAsync(m => m.GuestRespondId == id);
            if (guestRespond == null)
            {
                return NotFound();
            }

            return View(guestRespond);
        }

        // POST: GuestResponds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var guestRespond = await _context.GuestRespond.FindAsync(id);
            _context.GuestRespond.Remove(guestRespond);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GuestRespondExists(int id)
        {
            return _context.GuestRespond.Any(e => e.GuestRespondId == id);
        }
    }
}

RSVPApp/Views/GuestResponds/Create.cshtml
@model RSVPApp.Models.GuestRespond

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <p>Name:</p>
    @Html.TextBoxFor(c=>c.Name)<br/>
    <p>Email:</p>
    @Html.TextBoxFor(c=>c.Email)<br/>
    <p>Phone:</p>
    @Html.TextBoxFor(c=>c.Phone)<br/>
    <p>Will you show up?:</p>
    @Html.DropDownListFor(c=>c.Attend, new []{
        new SelectListItem(){
            Text = "Yes, I'm going", 
            Value = bool.TrueString
        }, 
        new SelectListItem(){
            Text = "No",
            Value = bool.FalseString
        }
    }, "Choose an option")<br/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
}

<hr />
@*<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Attend" class="control-label"></label>
                <input asp-for="Attend" class="form-control" />
                <span asp-validation-for="Attend" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

*@<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSVPApp/Views/GuestResponds/Delete.cshtml
@model RSVPApp.Models.GuestRespond

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GuestRespond</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Attend)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Attend)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GuestRespondId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RSVPApp/Views/GuestResponds/Details.cshtml
@model RSVPApp.Models.GuestRespond

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>GuestRespond</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Attend)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Attend)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.GuestRespondId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RSVPApp/Views/GuestResponds/Edit.cshtml
@model RSVPApp.Models.GuestRespond

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>GuestRespond</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GuestRespondId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Attend" class="control-label"></label>
                <input asp-for="Attend" class="form-control" />
                <span asp-validation-for="Attend" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RSVPApp/Views/GuestResponds/Index.cshtml
@model IEnumerable<RSVPApp.Models.GuestRespond>

@{
    ViewData["Title"] = "Index";
}

<h1>Guests</h1>

<p>
    <a asp-action="Create">Add new</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Attend)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Attend)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.GuestRespondId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.GuestRespondId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.GuestRespondId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

RSVPApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RVSPApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InvitationApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RVSPApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GuestResponds" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RVSPApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>